// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 웹 플랫폼 설정 추가
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtZd93xb-FsLx07OHhr69a_6pE52xYJQA',
    appId: '1:410981489784:web:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '410981489784',
    projectId: 'lifewisp-app',
    authDomain: 'lifewisp-app.firebaseapp.com',
    storageBucket: 'lifewisp-app.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZd93xb-FsLx07OHhr69a_6pE52xYJQA',
    appId: '1:410981489784:android:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '410981489784',
    projectId: 'lifewisp-app',
    storageBucket: 'lifewisp-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtZd93xb-FsLx07OHhr69a_6pE52xYJQA',
    appId: '1:410981489784:ios:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '410981489784',
    projectId: 'lifewisp-app',
    storageBucket: 'lifewisp-app.appspot.com',
    iosClientId: '410981489784-kksc1dm7fvr9bom6tkt87s0altfv08pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifewisp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'YOUR_MACOS_BUNDLE_ID',
  );
}